### PR TITLE
is this PR necessary?

### PR DESCRIPTION
**Pull request by drandreaskrueger**
don't know why but even after the last PR, in [MY](https://github.com/drandreaskrueger/iptv-stream-cleaner) repo it still says 

> This branch is 15 commits ahead of FutureSharks:master.

Perhaps this new PR fixes that?

### CODE REVIEW

**Comment by drandreaskrueger** [comment]
oh, and if you do intend to merge the PR, shall we rename it before? What would be a better summary title?

**Review by FutureSharks — APPROVED** [review]

**Comment by FutureSharks** [comment]
Not sure but we can merge it anyway 🙂

> What would be a better summary title?

For a low activity project like this one I don't think it matters so much.

**Comment by drandreaskrueger** [comment]
Thanks.

This is weird - [my repo now looks](https://github.com/drandreaskrueger/iptv-stream-cleaner) like this

Screenshot from 2021-07-03 16-15-39

 AFTER I did "fetch upstream" --> "fetch and merge"

What do I not get here?  
How come that I am still "ahead" even though you had just PR-merged all my commits, and I fetch-merged your PR-merge?

**Comment by FutureSharks** [comment]
I think because they have diverged too much. My master has only 4 commits while yours has 20.

I use this arrangement when working with forks: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork

**Comment by drandreaskrueger** [comment]
> My master has only 4 commits

yes, but no: Click on the [third](https://github.com/FutureSharks/iptv-stream-cleaner/commit/6e35153910f7bd5b629051ca7c3d634970fa663c), it contains 12 commits.

here is a compare:
https://github.com/FutureSharks/iptv-stream-cleaner/compare/FutureSharks:master...drandreaskrueger:master

**Comment by FutureSharks** [comment]
> yes, but no: Click on the third, it contains 12 commits.

That's 12 commits squashed into a single one. The comment is the comments from all those commits concatenated. But it's a single commit in my repo because I "squash" merged the PR. Squashing commits before merging to master is pretty common now as it keeps the commit history nice and clean 🙂

**Comment by drandreaskrueger** [comment]
Yes, I see. Well done.

The other problem however ... is strange. Why pressing the respective "fetch and merge" buttons in github did not solve it. Anyways:

I have now done this:

```
git remote add upstream git@github.com:FutureSharks/iptv-stream-cleaner.git
cat .git/config 

git fetch upstream
git branch -a

git reset --hard upstream/master
git push --force
```

and now it looks like this:

Screenshot from 2021-07-05 19-18-47

all good now: 

> this branch is even with ...

thanks

**Pull request merged**
